stages:
  - test

build:
  stage: build
  image: maven:3.8.5-openjdk-17 # Docker-образ с Maven и Java 17
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar # Сохраняем собранный JAR-артефакт
  only:
    - main # Запускаем стадию только на ветке main


test:
  stage: test
  image: maven:3.8.5-openjdk-17
  script:
    - mvn test # Запускаем все тесты
  only:
    - merge_requests # Выполняем тесты для merge-запросов


deploy:
  stage: deploy
  image: docker:20.10.16 # Используем Docker для развертывания
  services:
    - docker:dind # Docker-in-Docker для работы с контейнерами
  script:
    - docker build -t my-spring-app:latest .
    - docker run -d -p 8080:8080 my-spring-app:latest
  only:
    - main # Деплой выполняется только для ветки main